Add mash and capnproto (required by mash) recipes
wtsi-npg/npg_conda pull request #229
Opened 2021-03-18 15:05 UTC by mksanger

2021-03-25 15:53 UTC, mgcam commented
Tested by creating a few sketches and also by running `mash screen` on an existing sketch with previously screened data.

2021-03-29 13:37 UTC, kjsanger requested changes

2021-03-29 13:37 UTC, kjsanger commented on recipes/capnproto/0.7.0/build.sh
> +LD_LIBRARY_PATH=$PREFIX/lib ./configure --prefix="$PREFIX" \
LD_LIBRARY_PATH should be unnecessary here.

2021-03-29 13:37 UTC, kjsanger commented on recipes/mash/2.3/build.sh
> +LD_LIBRARY_PATH=$PREFIX/lib ./configure --prefix="$PREFIX" \
LD_LIBRARY_PATH should be unnecessary here.

2021-03-29 13:37 UTC, kjsanger commented on recipes/mash/2.3/meta.yaml
> +    - capnproto
Please check that this is required at runtime and if so, split the capnproto recipe into two sub-packages (one with the components required to build and one with the runtime components).

2021-04-07 14:15 UTC, merged